# This is the docker-compose file for in cloud (edge) development and production

version: "2.0.0"

services:
  prepit-edge-prod-server:
    container_name: prepit-edge-prod-server
    secrets:
      - prepit-secret
    image: ghcr.io/jerryyang666/prepit-edge:prod
    volumes:
      - ./edge_prod_volume:/app/volume_cache:rw
    networks:
      - prodnet
    depends_on:
      - nginx-server
      - redis-prod-server
  redis-prod-server:
    container_name: redis-prod-server
    image: redis/redis-stack-server:latest
    volumes:
      - ./redis_prod_volume:/data:rw
    networks:
      - prodnet
  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    environment:
      - DOMAIN1=edge-jp-tokyo-1.prepit-ai.com
    volumes:
      - ./files/nginx/conf.d/nginx.conf.template:/etc/nginx/templates/nginx.conf.template:ro
      - ./files/nginx/ssl:/etc/nginx/ssl:ro
      - ./files/certbot/www:/var/www/certbot:ro
      - ./files/certbot/conf:/etc/letsencrypt:ro
    networks:
      - prodnet
  certbot:
    container_name: certbot
    image: certbot/certbot
    volumes:
      - ./files/certbot/www:/var/www/certbot:rw
      - ./files/certbot/conf:/etc/letsencrypt:rw
      - ./files/certbot/logs:/var/log/letsencrypt:rw
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 24h & wait $${!}; done;'"

networks:
  prodnet:

secrets:
  prepit-secret:
    file: edcwsxqaz